---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:14
          resources:
            limits:
              memory: 150Mi
          volumeMounts:
            - mountPath: /data
              name: data
          env:
            - name: POSTGRES_DB
              value: quarkus
            - name: POSTGRES_USER
              value: quarkus
            - name: POSTGRES_PASSWORD
              value: quarkus
            - name: PGDATA
              value: /data/pgdata
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432

